{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "release-dotnet-helm-v2.serviceAccountName" . }}
  labels:
{{ include "release-dotnet-helm-v2.labels" . | indent 4 }}
{{- end -}}
